# Generated by Django 5.1.15 on 2026-05-09 15:29

import api.rls
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("api", "0090_attack_paths_cleanup_priority"),
    ]

    operations = [
        migrations.CreateModel(
            name="M365AuditLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("inserted_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("source_id", models.CharField(max_length=255)),
                ("timestamp", models.DateTimeField()),
                ("activity_display_name", models.CharField(blank=True, max_length=500)),
                ("category", models.CharField(blank=True, max_length=255)),
                ("operation_type", models.CharField(blank=True, max_length=255)),
                ("result", models.CharField(blank=True, max_length=100)),
                ("initiated_by", models.JSONField(blank=True, default=dict)),
                ("target_resources", models.JSONField(blank=True, default=list)),
                ("raw_event", models.JSONField(blank=True, default=dict)),
                (
                    "provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="secto_m365_audit_logs",
                        related_query_name="secto_m365_audit_log",
                        to="api.provider",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.tenant"
                    ),
                ),
            ],
            options={
                "db_table": "secto_m365_audit_logs",
                "abstract": False,
                "indexes": [
                    models.Index(
                        fields=["tenant_id", "provider", "timestamp"],
                        name="secto_audit_t_prov_ts",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="M365SignInLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("inserted_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("source_id", models.CharField(max_length=255)),
                ("timestamp", models.DateTimeField()),
                ("app_id", models.CharField(blank=True, max_length=255)),
                ("app_display_name", models.CharField(blank=True, max_length=255)),
                ("client_app_used", models.CharField(blank=True, max_length=100)),
                ("is_interactive", models.BooleanField(default=False)),
                ("session_id", models.CharField(blank=True, max_length=255)),
                ("status", models.JSONField(blank=True, default=dict)),
                ("location", models.JSONField(blank=True, default=dict)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_id", models.CharField(blank=True, max_length=255)),
                ("user_display_name", models.CharField(blank=True, max_length=255)),
                ("user_principal_name", models.CharField(blank=True, max_length=255)),
                ("raw_event", models.JSONField(blank=True, default=dict)),
                (
                    "provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="secto_m365_signin_logs",
                        related_query_name="secto_m365_signin_log",
                        to="api.provider",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.tenant"
                    ),
                ),
            ],
            options={
                "db_table": "secto_m365_signin_logs",
                "abstract": False,
                "indexes": [
                    models.Index(
                        fields=["tenant_id", "provider", "timestamp"],
                        name="secto_signin_t_prov_ts",
                    ),
                    models.Index(
                        fields=["tenant_id", "provider", "session_id", "timestamp"],
                        name="secto_signin_session_ts",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="M365UnifiedAuditLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("inserted_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("source_id", models.CharField(max_length=255)),
                ("timestamp", models.DateTimeField()),
                ("record_type", models.IntegerField(blank=True, null=True)),
                ("operation", models.CharField(blank=True, max_length=255)),
                ("workload", models.CharField(blank=True, max_length=255)),
                ("user_id", models.CharField(blank=True, max_length=500)),
                ("user_principal_name", models.CharField(blank=True, max_length=500)),
                ("client_ip", models.GenericIPAddressField(blank=True, null=True)),
                ("object_id", models.CharField(blank=True, max_length=1000)),
                ("raw_event", models.JSONField(blank=True, default=dict)),
                (
                    "provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="secto_m365_unified_audit_logs",
                        related_query_name="secto_m365_unified_audit_log",
                        to="api.provider",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.tenant"
                    ),
                ),
            ],
            options={
                "db_table": "secto_m365_unified_audit_logs",
                "abstract": False,
                "indexes": [
                    models.Index(
                        fields=["tenant_id", "provider", "timestamp"],
                        name="secto_unified_t_prov_ts",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="SectoLogCursor",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("inserted_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("signin_cursor_at", models.DateTimeField(blank=True, null=True)),
                ("audit_cursor_at", models.DateTimeField(blank=True, null=True)),
                (
                    "unified_audit_cursor_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "provider",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="secto_log_cursor",
                        related_query_name="secto_log_cursor",
                        to="api.provider",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.tenant"
                    ),
                ),
            ],
            options={
                "db_table": "secto_log_cursors",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SectoThreat",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("inserted_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("rule_id", models.CharField(max_length=255)),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("critical", "Critical"),
                            ("high", "High"),
                            ("medium", "Medium"),
                            ("low", "Low"),
                        ],
                        default="medium",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("open", "Open"), ("resolved", "Resolved")],
                        default="open",
                        max_length=20,
                    ),
                ),
                ("session_id", models.CharField(max_length=255)),
                ("first_seen", models.DateTimeField()),
                ("last_seen", models.DateTimeField()),
                ("affected_users", models.JSONField(blank=True, default=list)),
                ("source_ip_addresses", models.JSONField(blank=True, default=list)),
                ("countries", models.JSONField(blank=True, default=list)),
                ("related_events_count", models.PositiveIntegerField(default=0)),
                ("evidence", models.JSONField(blank=True, default=dict)),
                (
                    "provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="secto_threats",
                        related_query_name="secto_threat",
                        to="api.provider",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.tenant"
                    ),
                ),
            ],
            options={
                "db_table": "secto_threats",
                "abstract": False,
                "indexes": [
                    models.Index(
                        fields=["tenant_id", "provider", "last_seen"],
                        name="secto_threat_provider_seen",
                    ),
                    models.Index(
                        fields=["tenant_id", "rule_id", "status"],
                        name="secto_threat_rule_status",
                    ),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="m365auditlog",
            constraint=api.rls.RowLevelSecurityConstraint(
                "tenant_id",
                name="rls_on_m365auditlog",
                statements=["SELECT", "INSERT", "UPDATE", "DELETE"],
            ),
        ),
        migrations.AddConstraint(
            model_name="m365auditlog",
            constraint=models.UniqueConstraint(
                fields=("tenant_id", "provider", "source_id"),
                name="unique_secto_m365_audit_source",
            ),
        ),
        migrations.AddConstraint(
            model_name="m365signinlog",
            constraint=api.rls.RowLevelSecurityConstraint(
                "tenant_id",
                name="rls_on_m365signinlog",
                statements=["SELECT", "INSERT", "UPDATE", "DELETE"],
            ),
        ),
        migrations.AddConstraint(
            model_name="m365signinlog",
            constraint=models.UniqueConstraint(
                fields=("tenant_id", "provider", "source_id"),
                name="unique_secto_m365_signin_source",
            ),
        ),
        migrations.AddConstraint(
            model_name="m365unifiedauditlog",
            constraint=api.rls.RowLevelSecurityConstraint(
                "tenant_id",
                name="rls_on_m365unifiedauditlog",
                statements=["SELECT", "INSERT", "UPDATE", "DELETE"],
            ),
        ),
        migrations.AddConstraint(
            model_name="m365unifiedauditlog",
            constraint=models.UniqueConstraint(
                fields=("tenant_id", "provider", "source_id"),
                name="unique_secto_m365_unified_source",
            ),
        ),
        migrations.AddConstraint(
            model_name="sectologcursor",
            constraint=api.rls.RowLevelSecurityConstraint(
                "tenant_id",
                name="rls_on_sectologcursor",
                statements=["SELECT", "INSERT", "UPDATE", "DELETE"],
            ),
        ),
        migrations.AddConstraint(
            model_name="sectothreat",
            constraint=api.rls.RowLevelSecurityConstraint(
                "tenant_id",
                name="rls_on_sectothreat",
                statements=["SELECT", "INSERT", "UPDATE", "DELETE"],
            ),
        ),
        migrations.AddConstraint(
            model_name="sectothreat",
            constraint=models.UniqueConstraint(
                fields=("tenant_id", "provider", "rule_id", "session_id"),
                name="unique_secto_threat_session_rule",
            ),
        ),
    ]
